# Generated by Django 5.1.2 on 2024-11-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_case_beneficiary_case_end_date_case_funding_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
