# Generated by Django 5.1.2 on 2024-11-11 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_donation_options_and_more'),
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='campaign_creator',
            field=models.ForeignKey(limit_choices_to={'account_type': 'creator'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='userauths.userprofile'),
        ),
    ]
