# Generated by Django 5.1.2 on 2024-11-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_case_campaign_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='beneficiary',
        ),
    ]
