# Generated by Django 5.1.2 on 2024-11-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_case_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='raised_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
